### ISSUE TITLE
可以用魅族的接口判断是否含SmartBar

### ISSUE THREAD

**Issue by shawnlinboy** [ctiao/SmartBarUtility#1]
//先拜谢跳大
//同时分享一个判断有无SmartBar的官方方法 

public static boolean hasSmartBar() {
    try {
            Method method = Class.forName("android.os.Build").getMethod(
                    "hasSmartBar");
            return ((Boolean) method.invoke(null)).booleanValue();
        } catch (Exception e) {
    }

```
if (Build.DEVICE.equals("mx2")) {
    return true;
} else if (Build.DEVICE.equals("mx") || Build.DEVICE.equals("m9")) {
    return false;
}
       return false;
}
```

**Comment by ctiao** [comment]
这个不错,有时间收进来 :)
